import React from 'react';
import { Monitor, Server, Brain, Heart, Beaker, BarChart, Shield, Pill, Apple, Stethoscope, Sparkles, Database, Cloud, ArrowRight, ArrowDown, Activity, Users, FileText, Zap, Globe, Code } from 'lucide-react';

const HealthSystemArchitecture = () => {
  return (
    <div className="w-full bg-gradient-to-br from-slate-900 via-blue-900 to-purple-900 p-8 pb-16 overflow-x-auto">
      {/* Title Section */}
      <div className="text-center mb-8">
        <h2 className="text-5xl font-bold mb-4">
          <span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
            Multi-Agent Health Insight System Architecture
          </span>
        </h2>
        <p className="text-2xl text-gray-200 font-medium max-w-6xl mx-auto">
          Generated by the 3 Amigo Agents Pattern: Orchestrated medical specialists analyzing health data in real-time
        </p>
      </div>

      <div className="min-w-max mx-auto">
        {/* Top Row: Main Components */}
        <div className="flex items-stretch justify-center gap-8 mb-4">
          {/* Column 1: Frontend */}
          <div className="bg-gradient-to-b from-blue-500/20 to-cyan-500/20 rounded-xl p-6 border border-blue-500/30 w-80" style={{ minHeight: '480px' }}>
            <div className="text-center mb-4">
              <div className="w-20 h-20 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-full mx-auto mb-4 flex items-center justify-center">
                <Monitor className="w-12 h-12 text-white" />
              </div>
              <h3 className="text-3xl font-bold text-blue-300">Frontend</h3>
              <p className="text-gray-300 text-lg mt-1">React + Vite + TypeScript</p>
            </div>
            
            <div className="bg-blue-500/10 rounded-lg p-2 mb-3">
              <p className="text-blue-300 font-bold text-xl text-center">🖥️ User Interface Components:</p>
            </div>
            
            <div className="space-y-3">
              <div className="bg-white/10 rounded-lg p-3">
                <FileText className="w-6 h-6 text-blue-400 mb-1" />
                <div className="text-white font-medium text-lg">3-Panel Layout</div>
                <div className="text-gray-300 text-base">Thread • Chat • Team/Viz</div>
              </div>
              
              <div className="bg-white/10 rounded-lg p-3">
                <Users className="w-6 h-6 text-blue-400 mb-1" />
                <div className="text-white font-medium text-lg">Medical Team View</div>
                <div className="text-gray-300 text-base">Real-time agent status</div>
              </div>
              
              <div className="bg-white/10 rounded-lg p-3">
                <BarChart className="w-6 h-6 text-blue-400 mb-1" />
                <div className="text-white font-medium text-lg">Dynamic Charts</div>
                <div className="text-gray-300 text-base">React visualizations</div>
              </div>
              
              <div className="bg-blue-600/20 rounded-lg p-3">
                <Zap className="w-5 h-5 text-blue-400 inline mr-2" />
                <span className="text-blue-300 font-bold">SSE Real-time Updates</span>
              </div>
            </div>
          </div>

          {/* Arrow 1 */}
          <div className="flex flex-col items-center justify-center pt-24">
            <p className="text-blue-400 text-lg font-medium mb-1">EventSource</p>
            <ArrowRight className="w-12 h-12 text-blue-400" />
            <p className="text-gray-400 text-lg mt-1">streaming</p>
          </div>

          {/* Column 2: Backend + CMO */}
          <div className="bg-gradient-to-b from-green-500/20 to-emerald-500/20 rounded-xl p-6 border border-green-500/30 w-80 relative" style={{ minHeight: '480px' }}>
            <div className="text-center mb-4">
              <div className="w-20 h-20 bg-gradient-to-r from-green-500 to-emerald-500 rounded-full mx-auto mb-4 flex items-center justify-center">
                <Server className="w-12 h-12 text-white" />
              </div>
              <h3 className="text-3xl font-bold text-green-300">Backend API</h3>
              <p className="text-gray-300 text-lg mt-1">FastAPI + Orchestration</p>
            </div>
            
            <div className="bg-green-500/10 rounded-lg p-2 mb-3">
              <p className="text-green-300 font-bold text-xl text-center">🎯 Health Analyst Service:</p>
            </div>
            
            {/* CMO Section within Backend */}
            <div className="bg-gradient-to-b from-yellow-500/20 to-orange-500/20 rounded-lg p-3 mb-3 relative">
              {/* Claude Opus 4 label in top right */}
              <div className="absolute top-2 right-2 bg-yellow-600/20 rounded px-2 py-1">
                <div className="text-yellow-300 font-bold text-xs">Claude Opus 4</div>
              </div>
              
              <div className="flex items-center gap-2 mb-2">
                <Brain className="w-8 h-8 text-yellow-400" />
                <div className="text-yellow-300 font-bold text-lg">CMO Agent</div>
              </div>
              <div className="text-gray-300 text-sm mb-2">Chief Medical Officer</div>
              <div className="space-y-1 text-sm">
                <div className="text-gray-300">• Query complexity analysis</div>
                <div className="text-gray-300">• Specialist task creation</div>
                <div className="text-gray-300">• Results synthesis</div>
                <div className="text-gray-300">• Visualization request</div>
              </div>
            </div>
            
            <div className="space-y-2">
              <div className="bg-white/10 rounded-lg p-2">
                <div className="text-white font-medium">SSE Endpoints</div>
                <div className="text-gray-300 text-sm">Real-time streaming</div>
              </div>
              
              <div className="bg-white/10 rounded-lg p-2">
                <div className="text-white font-medium">Error Handling</div>
                <div className="text-gray-300 text-sm">Graceful degradation</div>
              </div>
            </div>

            {/* Arrow from CMO to Medical Team */}
            <div className="absolute left-full ml-1 top-64">
              <div className="flex flex-col items-center">
                <p className="text-green-400 text-lg font-medium mb-1 text-center">Orchestrates</p>
                <ArrowRight className="w-12 h-12 text-green-400" />
              </div>
            </div>
            
            {/* Arrow from CMO to Visualization */}
            <div className="absolute left-full ml-2 bottom-24">
              <div className="flex flex-col items-center">
                <p className="text-green-400 text-lg font-medium mb-1 text-center">Final Synthesis</p>
                <ArrowRight className="w-12 h-12 text-green-400" />
              </div>
            </div>
          </div>

          {/* Spacer for arrows */}
          <div className="w-12"></div>

          {/* Column 3: Medical Specialists + Visualization (stacked) */}
          <div className="w-80">
            {/* Top Section: Medical Team */}
            <div className="bg-gradient-to-b from-purple-500/20 to-pink-500/20 rounded-xl p-6 border border-purple-500/30 mb-4 relative" style={{ minHeight: '280px' }}>
              {/* Claude 3.7 Sonnet label in top right */}
              <div className="absolute top-2 right-2 bg-purple-600/20 rounded px-2 py-1">
                <div className="text-purple-300 font-bold text-xs">Claude 3.7 Sonnet</div>
              </div>
              
              <div className="text-center mb-3">
                <div className="w-16 h-16 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full mx-auto mb-3 flex items-center justify-center">
                  <Users className="w-10 h-10 text-white" />
                </div>
                <h3 className="text-2xl font-bold text-purple-300">Medical Team</h3>
                <p className="text-gray-300 text-base mt-1">8 Specialist Agents</p>
              </div>
              
              <div className="bg-purple-500/10 rounded-lg p-2 mb-2">
                <p className="text-purple-300 font-bold text-base text-center">👨‍⚕️ Parallel Analysis:</p>
              </div>
              
              <div className="grid grid-cols-2 gap-2">
                <div className="bg-white/10 rounded-lg p-2">
                  <Heart className="w-5 h-5 text-red-400 mb-1" />
                  <div className="text-white font-medium text-sm">Cardiology</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Beaker className="w-5 h-5 text-purple-400 mb-1" />
                  <div className="text-white font-medium text-sm">Laboratory</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Activity className="w-5 h-5 text-blue-400 mb-1" />
                  <div className="text-white font-medium text-sm">Endocrinology</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <BarChart className="w-5 h-5 text-cyan-400 mb-1" />
                  <div className="text-white font-medium text-sm">Data Analysis</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Shield className="w-5 h-5 text-green-400 mb-1" />
                  <div className="text-white font-medium text-sm">Preventive</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Pill className="w-5 h-5 text-orange-400 mb-1" />
                  <div className="text-white font-medium text-sm">Pharmacy</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Apple className="w-5 h-5 text-lime-400 mb-1" />
                  <div className="text-white font-medium text-sm">Nutrition</div>
                </div>
                
                <div className="bg-white/10 rounded-lg p-2">
                  <Stethoscope className="w-5 h-5 text-teal-400 mb-1" />
                  <div className="text-white font-medium text-sm">General</div>
                </div>
              </div>
            </div>

            {/* Bottom Section: Visualization */}
            <div className="bg-gradient-to-b from-pink-500/20 to-rose-500/20 rounded-xl p-4 border border-pink-500/30 relative" style={{ minHeight: '180px' }}>
              {/* Arrow from Medical Team to Visualization */}
              <div className="absolute -top-12 left-1/2 transform -translate-x-1/2">
                <div className="flex flex-col items-center">
                  <span className="text-purple-400 text-sm mb-1">synthesis</span>
                  <ArrowDown className="w-10 h-10 text-purple-400" />
                </div>
              </div>
              
              {/* Claude Opus 4 label in top right */}
              <div className="absolute top-2 right-2 bg-pink-600/20 rounded px-2 py-1">
                <div className="text-pink-300 font-bold text-xs">Claude Opus 4</div>
              </div>
              
              <div className="text-center mb-3">
                <div className="w-14 h-14 bg-gradient-to-r from-pink-500 to-rose-500 rounded-full mx-auto mb-2 flex items-center justify-center">
                  <Sparkles className="w-9 h-9 text-white" />
                </div>
                <h3 className="text-xl font-bold text-pink-300">Visualization Agent</h3>
                <p className="text-gray-300 text-sm mt-1">Dynamic Chart Generation</p>
              </div>
              
              <div className="bg-pink-500/10 rounded-lg p-2 mb-2">
                <p className="text-pink-300 font-bold text-sm text-center">📊 React Components:</p>
              </div>
              
              <div className="grid grid-cols-3 gap-2">
                <div className="bg-white/10 rounded-lg p-2">
                  <Code className="w-4 h-4 text-pink-400 mb-1" />
                  <div className="text-white text-xs">Time Series</div>
                </div>
                <div className="bg-white/10 rounded-lg p-2">
                  <BarChart className="w-4 h-4 text-pink-400 mb-1" />
                  <div className="text-white text-xs">Comparisons</div>
                </div>
                <div className="bg-white/10 rounded-lg p-2">
                  <Activity className="w-4 h-4 text-pink-400 mb-1" />
                  <div className="text-white text-xs">Distributions</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Single Arrow pointing down from Backend only */}
        <div className="flex items-start justify-center gap-8 mb-4" style={{ marginTop: '20px' }}>
          {/* Empty space under Frontend */}
          <div className="w-80 flex justify-center">
          </div>
          
          {/* Spacer */}
          <div className="w-12"></div>
          
          {/* Arrow under Backend */}
          <div className="w-80 flex justify-center">
            <div className="flex flex-col items-center">
              <ArrowDown className="w-12 h-12 text-green-400" />
              <p className="text-green-400 text-lg font-medium mt-1">Natural Language Health Queries</p>
            </div>
          </div>
          
          {/* Spacer */}
          <div className="w-12"></div>
          
          {/* Empty space under Specialists/Viz */}
          <div className="w-80 flex justify-center">
          </div>
        </div>

        {/* Bottom Row: Foundation Layer */}
        <div className="flex justify-center">
          <div className="bg-gradient-to-b from-indigo-500/20 to-violet-500/20 rounded-xl p-6 border border-indigo-500/30" style={{ width: '74rem' }}>
            <div className="grid grid-cols-3 gap-6">
              {/* Left: Pre-built MCP Tools */}
              <div className="flex items-center gap-4">
                <div className="w-20 h-20 bg-gradient-to-r from-indigo-500 to-blue-600 rounded-full flex items-center justify-center">
                  <Database className="w-12 h-12 text-white" />
                </div>
                <div>
                  <h3 className="text-3xl font-bold text-indigo-300">Pre-built MCP Tools</h3>
                  <p className="text-gray-300 text-lg">Data Access Layer</p>
                </div>
              </div>

              {/* Center: Tool Functions */}
              <div className="bg-gradient-to-r from-indigo-600/20 to-blue-600/20 rounded-lg px-6 py-3 flex items-center justify-center">
                <div>
                  <div className="text-indigo-300 font-bold text-lg mb-2">🔧 Available Tools:</div>
                  <div className="space-y-1">
                    <div className="text-white">• execute_health_query - Natural language queries</div>
                    <div className="text-white">• snowflake_import_analyze - Health record import</div>
                  </div>
                </div>
              </div>

              {/* Right: External Services */}
              <div className="bg-gradient-to-r from-violet-600/20 to-purple-600/20 rounded-lg px-6 py-3">
                <div className="text-lg font-bold text-violet-300 mb-2">☁️ External Services:</div>
                <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-base">
                  <div className="flex items-center gap-2">
                    <Cloud className="w-5 h-5 text-violet-400" />
                    <span className="text-white">Anthropic Claude API</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Database className="w-5 h-5 text-violet-400" />
                    <span className="text-white">Snowflake + Cortex</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HealthSystemArchitecture;